[LightDM]
greeter-user=lightdm
minimum-vt=7
log-directory=/var/log/lightdm
run-directory=/var/run/lightdm
cache-directory=/var/cache/lightdm

[Seat:*]
type=local
pam-service=lightdm
pam-greeter-service=lightdm-greeter
xserver-command=X
xserver-allow-tcp=false
greeter-session=slick-greeter
user-session=agenticos
greeter-hide-users=false
greeter-allow-guest=false
greeter-show-manual-login=true
allow-user-switching=true
allow-guest=false
