[Greeter]
background=/usr/share/backgrounds/agenticos/agenticos-login.png
background-color=#0b1020
draw-user-backgrounds=false
draw-grid=false

show-hostname=true
show-keyboard=true
show-a11y=true
show-power=true
show-clock=true
show-quit=true

logo=/usr/share/pixmaps/agenticos-logo.png

theme-name=Adwaita
font-name=Sans 11

enable-hidpi=auto
content-align=center
clock-format=%H:%M
